TDV.PlayerAPI.defineScript({ "definitions": [
 {
  "hfovMax": 120,
  "vfov": 180,
  "label": "test",
  "frames": [
   {
    "thumbnailUrl": "media/panorama_31DCDF06_3682_2007_4193_177B49D8D523_t.jpg",
    "stereoSphere": {
     "levels": [
      {
       "url": "media/panorama_31DCDF06_3682_2007_4193_177B49D8D523_hq.jpeg",
       "height": 4096,
       "class": "ImageResourceLevel",
       "width": 4096
      },
      {
       "url": "media/panorama_31DCDF06_3682_2007_4193_177B49D8D523.jpeg",
       "height": 3217,
       "class": "ImageResourceLevel",
       "width": 3217
      }
     ],
     "class": "ImageResource"
    },
    "class": "SphericPanoramaFrame"
   }
  ],
  "hfovMin": 60,
  "thumbnailUrl": "media/panorama_31DCDF06_3682_2007_4193_177B49D8D523_t.jpg",
  "id": "panorama_31DCDF06_3682_2007_4193_177B49D8D523",
  "class": "Panorama",
  "partial": false,
  "pitch": 0,
  "hfov": 360
 },
 {
  "viewerArea": "this.MainViewer",
  "buttonCardboardView": {
   "height": 23,
   "transparencyActive": false,
   "paddingRight": 0,
   "maxWidth": 35,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 1,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_3FCB9635_3682_2004_41B1_3A046A27EC9F.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 1,
   "backgroundOpacity": 0,
   "maxHeight": 23,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_3FCB9635_3682_2004_41B1_3A046A27EC9F",
   "width": 35,
   "horizontalAlign": "center"
  },
  "touchControlMode": "drag_acceleration",
  "preloadEnabled": false,
  "buttonZoomOut": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CE_E0BE2C156B35.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CE_E0BE2C156B35_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CE_E0BE2C156B35_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41CE_E0BE2C156B35",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonPause": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "toggle",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41C8_9487966219ED.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41C8_9487966219ED_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41C8_9487966219ED",
   "width": 40,
   "horizontalAlign": "center"
  },
  "displayPlaybackBar": true,
  "buttonMoveRight": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41BD_DE68C880FC1E.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41BD_DE68C880FC1E_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41BD_DE68C880FC1E_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41BD_DE68C880FC1E",
   "width": 40,
   "horizontalAlign": "center"
  },
  "gyroscopeVerticalDraggingEnabled": true,
  "buttonMoveUp": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41B5_0CA08581B09B.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41B5_0CA08581B09B_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41B5_0CA08581B09B_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41B5_0CA08581B09B",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonPlayLeft": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D3_547F7647C674.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D3_547F7647C674_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D3_547F7647C674_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41D3_547F7647C674",
   "width": 40,
   "horizontalAlign": "center"
  },
  "id": "MainViewerPanoramaPlayer",
  "class": "PanoramaPlayer",
  "buttonPlayRight": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D0_E8AB54929A60.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D0_E8AB54929A60_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D0_E8AB54929A60_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41D0_E8AB54929A60",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonZoomIn": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41A4_95868C6A0842.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41A4_95868C6A0842_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41A4_95868C6A0842_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41A4_95868C6A0842",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonMoveDown": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CC_17B487E3D0C5.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CC_17B487E3D0C5_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41CC_17B487E3D0C5_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41CC_17B487E3D0C5",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonRestart": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D1_62725E030F65.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D1_62725E030F65_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D1_62725E030F65_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41D1_62725E030F65",
   "width": 40,
   "horizontalAlign": "center"
  },
  "buttonMoveLeft": {
   "height": 40,
   "transparencyActive": false,
   "paddingRight": 0,
   "borderSize": 0,
   "borderRadius": 0,
   "shadow": false,
   "minHeight": 0,
   "paddingLeft": 0,
   "mode": "push",
   "verticalAlign": "middle",
   "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D5_532104041B82.png",
   "rollOverIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D5_532104041B82_rollover.png",
   "class": "IconButton",
   "paddingTop": 0,
   "minWidth": 0,
   "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_41D5_532104041B82_pressed.png",
   "backgroundOpacity": 0,
   "paddingBottom": 0,
   "cursor": "hand",
   "id": "IconButton_55DC4FA8_5E27_15CF_41D5_532104041B82",
   "width": 40,
   "horizontalAlign": "center"
  },
  "mouseControlMode": "drag_acceleration"
 },
 {
  "id": "panorama_31DCDF06_3682_2007_4193_177B49D8D523_camera",
  "class": "PanoramaCamera",
  "initialPosition": {
   "pitch": 0,
   "class": "PanoramaCameraPosition",
   "yaw": 0
  },
  "initialSequence": {
   "restartMovementOnUserInteraction": false,
   "movements": [
    {
     "yawSpeed": 7.96,
     "easing": "cubic_in",
     "yawDelta": 18.5,
     "class": "DistancePanoramaCameraMovement"
    },
    {
     "yawSpeed": 7.96,
     "easing": "linear",
     "yawDelta": 323,
     "class": "DistancePanoramaCameraMovement"
    },
    {
     "yawSpeed": 7.96,
     "easing": "cubic_out",
     "yawDelta": 18.5,
     "class": "DistancePanoramaCameraMovement"
    }
   ],
   "class": "PanoramaCameraSequence"
  },
  "automaticZoomSpeed": 10
 },
 {
  "items": [
   {
    "media": "this.panorama_31DCDF06_3682_2007_4193_177B49D8D523",
    "camera": "this.panorama_31DCDF06_3682_2007_4193_177B49D8D523_camera",
    "player": "this.MainViewerPanoramaPlayer",
    "class": "PanoramaPlayListItem"
   }
  ],
  "id": "mainPlayList",
  "class": "PlayList"
 }
], "children": [
 {
  "toolTipBorderSize": 1,
  "toolTipPaddingTop": 4,
  "playbackBarProgressBorderRadius": 0,
  "progressBarBorderSize": 0,
  "transitionMode": "blending",
  "top": 0,
  "toolTipTextShadowOpacity": 0,
  "toolTipShadowColor": "#333333",
  "borderRadius": 0,
  "toolTipShadowHorizontalLength": 0,
  "shadow": false,
  "paddingLeft": 0,
  "toolTipFontFamily": "Arial",
  "toolTipFontWeight": "normal",
  "playbackBarProgressBorderColor": "#000000",
  "playbackBarBorderRadius": 4,
  "toolTipBorderColor": "#767676",
  "toolTipBorderRadius": 3,
  "toolTipFontSize": 12,
  "toolTipTextShadowBlurRadius": 3,
  "playbackBarHeadBorderRadius": 0,
  "class": "ViewerArea",
  "toolTipOpacity": 1,
  "playbackBarProgressOpacity": 1,
  "progressLeft": 10,
  "playbackBarHeadBorderColor": "#000000",
  "toolTipBackgroundColor": "#F6F6F6",
  "toolTipShadowOpacity": 1,
  "playbackBarHeadShadowBlurRadius": 3,
  "playbackBarLeft": 0,
  "playbackBarBorderSize": 2,
  "progressBackgroundColorRatios": [
   0,
   1
  ],
  "paddingBottom": 0,
  "playbackBarBackgroundOpacity": 1,
  "minWidth": 100,
  "minHeight": 50,
  "id": "MainViewer",
  "toolTipShadowSpread": 0,
  "toolTipPaddingRight": 6,
  "toolTipShadowBlurRadius": 3,
  "borderSize": 0,
  "progressRight": 10,
  "playbackBarHeadHeight": 30,
  "progressOpacity": 1,
  "playbackBarHeadBorderSize": 0,
  "toolTipPaddingLeft": 6,
  "paddingRight": 0,
  "progressBarBackgroundColorDirection": "vertical",
  "playbackBarHeadBackgroundColorRatios": [
   0,
   1
  ],
  "playbackBarHeadShadow": true,
  "toolTipFontColor": "#606060",
  "progressBarBorderColor": "#000000",
  "playbackBarHeadShadowHorizontalLength": 0,
  "progressBarBackgroundColorRatios": [
   0,
   1
  ],
  "toolTipShadowVerticalLength": 0,
  "playbackBarHeadOpacity": 1,
  "progressBackgroundOpacity": 1,
  "height": "100%",
  "playbackBarHeadShadowVerticalLength": 0,
  "progressBackgroundColorDirection": "vertical",
  "playbackBarOpacity": 1,
  "playbackBarHeadShadowColor": "#000000",
  "playbackBarHeadBackgroundColor": [
   "#111111",
   "#666666"
  ],
  "width": "100%",
  "progressBarOpacity": 1,
  "playbackBarBottom": 10,
  "progressBorderColor": "#AAAAAA",
  "progressBottom": 1,
  "progressBarBackgroundColor": [
   "#222222",
   "#444444"
  ],
  "progressHeight": 20,
  "progressBackgroundColor": [
   "#EEEEEE",
   "#CCCCCC"
  ],
  "progressBorderSize": 2,
  "playbackBarProgressBackgroundColorDirection": "vertical",
  "toolTipFontStyle": "normal",
  "playbackBarHeadBackgroundColorDirection": "vertical",
  "paddingTop": 0,
  "toolTipPaddingBottom": 4,
  "playbackBarBackgroundColor": [
   "#EEEEEE",
   "#CCCCCC"
  ],
  "playbackBarHeadShadowOpacity": 0.7,
  "left": 0,
  "progressBorderRadius": 4,
  "playbackBarProgressBackgroundColorRatios": [
   0,
   1
  ],
  "playbackBarHeight": 20,
  "playbackBarProgressBackgroundColor": [
   "#222222",
   "#444444"
  ],
  "playbackBarProgressBorderSize": 0,
  "playbackBarBackgroundColorDirection": "vertical",
  "playbackBarHeadWidth": 6,
  "playbackBarRight": 0,
  "playbackBarBorderColor": "#AAAAAA",
  "toolTipTextShadowColor": "#000000",
  "progressBarBorderRadius": 4
 },
 {
  "scrollBarColor": "#000000",
  "height": 185,
  "layout": "horizontal",
  "paddingRight": 0,
  "width": "100%",
  "scrollBarOpacity": 0.5,
  "borderSize": 0,
  "bottom": "0%",
  "children": [
   {
    "scrollBarColor": "#000000",
    "height": 184.78,
    "layout": "horizontal",
    "paddingRight": 0,
    "scrollBarOpacity": 0.5,
    "borderSize": 0,
    "children": [
     "this.IconButton_55DC4FA8_5E27_15CF_41CE_E0BE2C156B35",
     "this.IconButton_55DC4FA8_5E27_15CF_41D1_62725E030F65",
     "this.IconButton_55DC4FA8_5E27_15CF_41D3_547F7647C674",
     "this.IconButton_55DC4FA8_5E27_15CF_41D5_532104041B82",
     {
      "scrollBarColor": "#000000",
      "borderSize": 0,
      "layout": "vertical",
      "paddingRight": 0,
      "scrollBarOpacity": 0.5,
      "children": [
       "this.IconButton_55DC4FA8_5E27_15CF_41B5_0CA08581B09B",
       "this.IconButton_55DC4FA8_5E27_15CF_41C8_9487966219ED",
       "this.IconButton_55DC4FA8_5E27_15CF_41CC_17B487E3D0C5"
      ],
      "borderRadius": 0,
      "contentOpaque": false,
      "shadow": false,
      "height": "100%",
      "paddingLeft": 0,
      "scrollBarVisible": "rollOver",
      "verticalAlign": "middle",
      "paddingTop": 0,
      "scrollBarWidth": 10,
      "class": "Container",
      "minWidth": 20,
      "scrollBarMargin": 2,
      "backgroundOpacity": 0,
      "overflow": "hidden",
      "paddingBottom": 0,
      "id": "Container_55DC4FA8_5E27_15CF_41BD_E12B3B6C43C0",
      "width": 40,
      "minHeight": 20,
      "horizontalAlign": "center",
      "gap": 4
     },
     "this.IconButton_55DC4FA8_5E27_15CF_41BD_DE68C880FC1E",
     "this.IconButton_55DC4FA8_5E27_15CF_41D0_E8AB54929A60",
     {
      "height": 40,
      "transparencyActive": false,
      "paddingRight": 0,
      "borderSize": 0,
      "borderRadius": 0,
      "shadow": false,
      "minHeight": 0,
      "paddingLeft": 0,
      "mode": "toggle",
      "verticalAlign": "middle",
      "iconURL": "skin/IconButton_55DC4FA8_5E27_15CF_4176_27D8664CB29D.png",
      "class": "IconButton",
      "paddingTop": 0,
      "minWidth": 0,
      "pressedIconURL": "skin/IconButton_55DC4FA8_5E27_15CF_4176_27D8664CB29D_pressed.png",
      "backgroundOpacity": 0,
      "paddingBottom": 0,
      "cursor": "hand",
      "id": "IconButton_55DC4FA8_5E27_15CF_4176_27D8664CB29D",
      "width": 40,
      "horizontalAlign": "center"
     },
     "this.IconButton_55DC4FA8_5E27_15CF_41A4_95868C6A0842"
    ],
    "borderRadius": 0,
    "shadow": false,
    "minHeight": 20,
    "paddingLeft": 0,
    "contentOpaque": false,
    "scrollBarVisible": "rollOver",
    "verticalAlign": "middle",
    "scrollBarWidth": 10,
    "class": "Container",
    "paddingTop": 0,
    "minWidth": 392,
    "scrollBarMargin": 2,
    "backgroundOpacity": 0,
    "overflow": "hidden",
    "paddingBottom": 0,
    "id": "Container_55DC4FA8_5E27_15CF_419E_B6601832ABA2",
    "width": 392.01,
    "horizontalAlign": "center",
    "gap": 4
   },
   "this.IconButton_3FCB9635_3682_2004_41B1_3A046A27EC9F"
  ],
  "minHeight": 1,
  "contentOpaque": false,
  "borderRadius": 0,
  "paddingLeft": 0,
  "shadow": false,
  "scrollBarVisible": "rollOver",
  "verticalAlign": "top",
  "scrollBarWidth": 10,
  "class": "Container",
  "paddingTop": 0,
  "left": "0%",
  "scrollBarMargin": 2,
  "backgroundOpacity": 0,
  "minWidth": 1,
  "overflow": "scroll",
  "paddingBottom": 0,
  "gap": 1,
  "horizontalAlign": "center"
 }
], 
 "scrollBarColor": "#000000",
 "borderSize": 0,
 "layout": "absolute",
 "buttonToggleMute": "this.IconButton_55DC4FA8_5E27_15CF_4176_27D8664CB29D",
 "paddingRight": 0,
 "start": "this.visibleComponentsIfPlayerFlagEnabled([this.IconButton_3FCB9635_3682_2004_41B1_3A046A27EC9F], 'cardboardAvailable'); this.mainPlayList.set('selectedIndex', 0)",
 "scrollBarOpacity": 0.5,
 "scripts": {
  "setMediaBehaviour": function(playList, index, mediaDispatcher){    var self = this;   var stateChangeFunction = function(event){       if(event.data.state == 'stopped'){           dispose();       }   };   var changeFunction = function(){       var index = playListDispatcher.get('selectedIndex');       if(index != -1){           indexDispatcher = index;           dispose();       }   };   var dispose = function(){       if(!playListDispatcher) return;       playList.set('selectedIndex', -1);       if(panoramaSequence && panoramaSequenceIndex != -1){           if(panoramaSequence) {               if(panoramaSequenceIndex > 0 && panoramaSequence.get('movements')[panoramaSequenceIndex-1].get('class') == 'TargetPanoramaCameraMovement'){                   var initialPosition = camera.get('initialPosition');                   var oldYaw = initialPosition.get('yaw');                   var oldPitch = initialPosition.get('pitch');                   var oldHfov = initialPosition.get('hfov');                   var previousMovement = panoramaSequence.get('movements')[panoramaSequenceIndex-1];                   initialPosition.set('yaw', previousMovement.get('targetYaw'));                   initialPosition.set('pitch', previousMovement.get('targetPitch'));                   initialPosition.set('hfov', previousMovement.get('targetHfov'));                   var restoreInitialPositionFunction = function(event){                       initialPosition.set('yaw', oldYaw);                       initialPosition.set('pitch', oldPitch);                       initialPosition.set('hfov', oldHfov);                       itemDispatcher.unbind('end', restoreInitialPositionFunction, self);                   };                   itemDispatcher.bind('end', restoreInitialPositionFunction, self);               }               panoramaSequence.set('movementIndex', panoramaSequenceIndex);           }       }       playListDispatcher.set('selectedIndex', indexDispatcher);       if(player){           player.unbind('stateChange', stateChangeFunction, self);       }       if(sameViewerArea){           if(playList != playListDispatcher)               playListDispatcher.unbind('change', changeFunction, self);       }       else{           viewerArea.set('visible', false);       }       playListDispatcher = undefined;   };   if(!mediaDispatcher){       var currentIndex = playList.get('selectedIndex');       var currentPlayer = (currentIndex != -1) ? playList.get('items')[playList.get('selectedIndex')].get('player') : this.getActivePlayerWithViewer(this.MainViewer);       if(currentPlayer) {           var playerClass = currentPlayer.get('class');           if(playerClass == 'PanoramaPlayer') mediaDispatcher = currentPlayer.get('panorama');           else if(playerClass == 'VideoPlayer' || playerClass == 'Video360Player') mediaDispatcher = currentPlayer.get('video');           else if(playerClass == 'PhotoAlbumPlayer') mediaDispatcher = currentPlayer.get('photoAlbum');           else if(playerClass == 'MapPlayer') mediaDispatcher = currentPlayer.get('map');       }   }   var playListDispatcher = mediaDispatcher ? this.getPlayListWithMedia(mediaDispatcher, true) : undefined;   if(!playListDispatcher){       playList.set('selectedIndex', index);       return;   }   var indexDispatcher = playListDispatcher.get('selectedIndex');   if(playList.get('selectedIndex') == index || indexDispatcher == -1){       return;   }   var item = playList.get('items')[index];   var itemDispatcher = playListDispatcher.get('items')[indexDispatcher];   var viewerArea = item.get('player').get('viewerArea');   var sameViewerArea = viewerArea == itemDispatcher.get('player').get('viewerArea');   if(sameViewerArea){       if(playList != playListDispatcher){           playListDispatcher.set('selectedIndex', -1);           playListDispatcher.bind('change', changeFunction, this);       }   }   else{       viewerArea.set('visible', true);   }   var panoramaSequenceIndex = -1;   var panoramaSequence = undefined;   var camera = itemDispatcher.get('camera');   if(camera){       panoramaSequence = camera.get('initialSequence');       if(panoramaSequence) {           panoramaSequenceIndex = panoramaSequence.get('movementIndex');       }   }   playList.set('selectedIndex', index);   var player = undefined;   if(item.get('player') != itemDispatcher.get('player')){       player = item.get('player');       player.bind('stateChange', stateChangeFunction, this);   }   this.executeFunctionWhenChange(playList, index, dispose); },
  "loopAlbum": function(playList, index){    var playListItem = playList.get('items')[index];   var player = playListItem.get('player');   var loopFunction = function(){       player.play();   };   this.executeFunctionWhenChange(playList, index, loopFunction); },
  "fixTogglePlayPauseButton": function(player){    var state = player.get('state');   var button = player.get('buttonPlayPause');   if(typeof button !== 'undefined' && player.get('state') == 'playing'){       button.set('pressed', true);   } },
  "loadFromCurrentMediaPlayList": function(playList, delta){    var currentIndex = playList.get('selectedIndex');   var totalItems = playList.get('items').length;   var newIndex = (currentIndex + delta) % totalItems;   while(newIndex < 0){       newIndex = totalItems + newIndex;   };   if(currentIndex != newIndex){       playList.set('selectedIndex', newIndex);   }; },
  "isCardboardViewMode": function(){    var players = this.getByClassName('PanoramaPlayer');   return players.length > 0 && players[0].get('viewMode') == 'cardboard'; },
  "pauseCurrentPlayers": function(onlyPauseCameraIfPanorama){    var players = this.getByClassName('PanoramaPlayer');   players = players.concat(this.getByClassName('VideoPlayer'));   players = players.concat(this.getByClassName('Video360Player'));   players = players.concat(this.getByClassName('PhotoAlbumPlayer'));   var i = players.length;   while(i-- > 0){       var player = players[i];       if(player.get('state') == 'playing') {           if(onlyPauseCameraIfPanorama && player.get('class') == 'PanoramaPlayer' && typeof player.get('video') === 'undefined'){               player.pauseCamera();           }           else{               player.pause();           }       }       else {           players.splice(i, 1);       }   }   return players; },
  "shareTwitter": function(url){    window.open('https://twitter.com/intent/tweet?source=webclient&url=' + url, '_blank'); },
  "pauseGlobalAudiosWhilePlayItem": function(playList, index, caller){    var audios = window.currentGlobalAudios;   if(!audios) return;   var resumeFunction = this.resumeGlobalAudios;   var endFunction = function(){       if(playList.get('selectedIndex') != index) {           resumeFunction(caller);       }   };   this.pauseGlobalAudios(caller);   this.executeFunctionWhenChange(playList, index, endFunction, endFunction); },
  "setMapLocation": function(panoramaPlayListItem, mapPlayer){    var resetFunction = function(){       panoramaPlayListItem.unbind('stop', resetFunction, this);       player.set('mapPlayer', null);   };   panoramaPlayListItem.bind('stop', resetFunction, this);   var player = panoramaPlayListItem.get('player');   player.set('mapPlayer', mapPlayer); },
  "showComponentsWhileMouseOver": function(parentComponent, components, durationVisibleWhileOut){    var setVisibility = function(visible){       for(var i = 0, length = components.length; i<length; i++){           components[i].set('visible', visible);       }   };   if (this.rootPlayer.touchEnabled){       setVisibility(true);   } else {       var timeoutID = -1;       var rollOverFunction = function(){           setVisibility(true);           if(timeoutID >= 0) clearTimeout(timeoutID);           parentComponent.unbind('rollOver', rollOverFunction, this);           parentComponent.bind('rollOut', rollOutFunction, this);       };       var rollOutFunction = function(){           var timeoutFunction = function(){               setVisibility(false);               parentComponent.unbind('rollOver', rollOverFunction, this);           };           parentComponent.unbind('rollOut', rollOutFunction, this);           parentComponent.bind('rollOver', rollOverFunction, this);           timeoutID = setTimeout(timeoutFunction, durationVisibleWhileOut);       };       parentComponent.bind('rollOver', rollOverFunction, this);   } },
  "pauseGlobalAudio": function(audio){    var audios = window.currentGlobalAudios;   if(audios){       audio = audios[audio.get('id')];   }   audio.pause(); },
  "shareGoogle": function(url){    window.open('https://plus.google.com/share?url=' + url, '_blank'); },
  "showPopupMedia": function(w, media, playList, popupMaxWidth, popupMaxHeight, autoCloseWhenFinished, containsAudio){    var self = this;   var closeFunction = function(){       self.MainViewer.set('toolTipEnabled', true);       this.resumePlayers(playersPaused, !containsAudio);       if(isVideo) {           this.unbind('resize', resizeFunction, this);       }       w.unbind('close', closeFunction, this);   };   var endFunction = function(){       w.hide();   };   var resizeFunction = function(){       var parentWidth = self.get('actualWidth');       var parentHeight = self.get('actualHeight');       var mediaWidth = media.get('width');       var mediaHeight = media.get('height');       var popupMaxWidthNumber = parseFloat(popupMaxWidth) / 100;       var popupMaxHeightNumber = parseFloat(popupMaxHeight) / 100;       var windowWidth = popupMaxWidthNumber * parentWidth;       var windowHeight = popupMaxHeightNumber * parentHeight;       var footerHeight = w.get('footerHeight');       var headerHeight = w.get('headerHeight');       if(!headerHeight) {           var closeButtonHeight = w.get('closeButtonIconHeight') + w.get('closeButtonPaddingTop') + w.get('closeButtonPaddingBottom');           var titleHeight = w.get('titleFontSize') + w.get('titlePaddingTop') + w.get('titlePaddingBottom');           headerHeight = closeButtonHeight > titleHeight ? closeButtonHeight : titleHeight;           headerHeight += w.get('headerPaddingTop') + w.get('headerPaddingBottom');       }       if(!footerHeight) {           footerHeight = 0;       }       var contentWindowWidth = windowWidth - w.get('bodyPaddingLeft') - w.get('bodyPaddingRight') - w.get('paddingLeft') - w.get('paddingRight');       var contentWindowHeight = windowHeight - headerHeight - footerHeight - w.get('bodyPaddingTop') - w.get('bodyPaddingBottom') - w.get('paddingTop') - w.get('paddingBottom');       var parentAspectRatio = contentWindowWidth / contentWindowHeight;       var mediaAspectRatio = mediaWidth / mediaHeight;       if(parentAspectRatio > mediaAspectRatio) {           windowWidth = contentWindowHeight * mediaAspectRatio + w.get('bodyPaddingLeft') + w.get('bodyPaddingRight') + w.get('paddingLeft') + w.get('paddingRight');       }       else {           windowHeight = contentWindowWidth / mediaAspectRatio + headerHeight + footerHeight + w.get('bodyPaddingTop') + w.get('bodyPaddingBottom') + w.get('paddingTop') + w.get('paddingBottom');       }       if(windowWidth > parentWidth * popupMaxWidthNumber) {           windowWidth = parentWidth * popupMaxWidthNumber;       }       if(windowHeight > parentHeight * popupMaxHeightNumber) {           windowHeight = parentHeight * popupMaxHeightNumber;       }       w.set('width', windowWidth);       w.set('height', windowHeight);       w.set('x', (parentWidth - w.get('actualWidth')) * 0.5);       w.set('y', (parentHeight - w.get('actualHeight')) * 0.5);   };   if(autoCloseWhenFinished){       this.executeFunctionWhenChange(playList, 0, endFunction);   }   var isVideo = media.get('class') == 'Video';   if(isVideo){       this.bind('resize', resizeFunction, this);       resizeFunction();   }   else {       w.set('width', popupMaxWidth);       w.set('height', popupMaxHeight);   }   this.MainViewer.set('toolTipEnabled', false);   var playersPaused = this.pauseCurrentPlayers(!containsAudio);   w.bind('close', closeFunction, this);   w.show(this, true); },
  "pauseGlobalAudios": function(caller){    var audios = window.currentGlobalAudios;   window.currentGlobalAudiosActionCaller = caller;   if(!audios) return;   for(var audio in audios){       audios[audio].pause();   } },
  "showPopupImage": function(image, toggleImage, customWidth, customHeight, showEffect, hideEffect, closeButtonProperties, autoCloseMilliSeconds, audio, stopBackgroundAudio, loadedCallback, hideCallback){    var self = this;   var closed = false;   var playerClickFunction = function() {       zoomImage.unbind('loaded', loadedFunction, self);       hideFunction();   };   var clearAutoClose = function(){       zoomImage.unbind('click', clearAutoClose, this);       if(timeoutID != undefined){           clearTimeout(timeoutID);       }   };   var loadedFunction = function(){       self.unbind('click', playerClickFunction, self);       veil.set('visible', true);       setCloseButtonPosition();       closeButton.set('visible', true);       zoomImage.unbind('loaded', loadedFunction, this);       zoomImage.bind('userInteractionStart', userInteractionStartFunction, this);       zoomImage.bind('userInteractionEnd', userInteractionEndFunction, this);       timeoutID = setTimeout(timeoutFunction, 200);   };   var timeoutFunction = function(){       timeoutID = undefined;       if(autoCloseMilliSeconds){           var autoCloseFunction = function(){               hideFunction();           };           zoomImage.bind('click', clearAutoClose, this);           timeoutID = setTimeout(autoCloseFunction, autoCloseMilliSeconds);       }       zoomImage.bind('backgroundClick', hideFunction, this);       if(toggleImage) {           zoomImage.bind('click', toggleFunction, this);           zoomImage.set('imageCursor', 'hand');       }       closeButton.bind('click', hideFunction, this);       if(loadedCallback)           loadedCallback();   };   var hideFunction = function() {       self.MainViewer.set('toolTipEnabled', true);       closed = true;       if(timeoutID)           clearTimeout(timeoutID);       if(autoCloseMilliSeconds)           clearAutoClose();       if(hideCallback)           hideCallback();       zoomImage.set('visible', false);       if(hideEffect && hideEffect.get('duration') > 0){           hideEffect.bind('end', endEffectFunction, this);       }       else{           zoomImage.set('image', null);       }       closeButton.set('visible', false);       veil.set('visible', false);       self.unbind('click', playerClickFunction, self);       zoomImage.unbind('backgroundClick', hideFunction, this);       zoomImage.unbind('userInteractionStart', userInteractionStartFunction, this);       zoomImage.unbind('userInteractionEnd', userInteractionEndFunction, this, true);       if(toggleImage) {           zoomImage.unbind('click', toggleFunction, this);           zoomImage.set('cursor', 'default');       }       closeButton.unbind('click', hideFunction, this);       self.resumePlayers(playersPaused, audio == null || stopBackgroundAudio);       if(audio){           if(stopBackgroundAudio){               self.resumeGlobalAudios();           }           self.stopGlobalAudio(audio);       }   };   var endEffectFunction = function() {       zoomImage.set('image', null);       hideEffect.unbind('end', endEffectFunction, this);   };   var toggleFunction = function() {       zoomImage.set('image', isToggleVisible() ? image : toggleImage);   };   var isToggleVisible = function() {       return zoomImage.get('image') == toggleImage;   };   var setCloseButtonPosition = function() {       var right = zoomImage.get('actualWidth') - zoomImage.get('imageLeft') - zoomImage.get('imageWidth') + 10;       var top = zoomImage.get('imageTop') + 10;       if(right < 10) right = 10;       if(top < 10) top = 10;       closeButton.set('right', right);       closeButton.set('top', top);   };   var userInteractionStartFunction = function() {       if(timeoutUserInteractionID){           clearTimeout(timeoutUserInteractionID);           timeoutUserInteractionID = undefined;       }       else{           closeButton.set('visible', false);       }   };   var userInteractionEndFunction = function() {       if(!closed){           timeoutUserInteractionID = setTimeout(userInteractionTimeoutFunction, 300);       }   };   var userInteractionTimeoutFunction = function() {       timeoutUserInteractionID = undefined;       closeButton.set('visible', true);       setCloseButtonPosition();   };   this.MainViewer.set('toolTipEnabled', false);   var veil = this.veilPopupPanorama;   var zoomImage = this.zoomImagePopupPanorama;   var closeButton = this.closeButtonPopupPanorama;   if(closeButtonProperties){       for(var key in closeButtonProperties){           closeButton.set(key, closeButtonProperties[key]);       }   }   var playersPaused = this.pauseCurrentPlayers(audio == null || !stopBackgroundAudio);   if(audio){       if(stopBackgroundAudio){           this.pauseGlobalAudios();       }       this.playGlobalAudio(audio);   }   var timeoutID = undefined;   var timeoutUserInteractionID = undefined;   zoomImage.bind('loaded', loadedFunction, this);   setTimeout(function(){ self.bind('click', playerClickFunction, self, false); }, 0);   zoomImage.set('image', image);   zoomImage.set('customWidth', customWidth);   zoomImage.set('customHeight', customHeight);   zoomImage.set('showEffect', showEffect);   zoomImage.set('hideEffect', hideEffect);   zoomImage.set('visible', true);   return zoomImage; },
  "playAudioList": function(audios){    if(audios.length == 0) return;   var currentAudioCount = -1;   var currentAudio;   var playGlobalAudioFunction = this.playGlobalAudio;   var playNext = function(){       if(++currentAudioCount >= audios.length)           currentAudioCount = 0;       currentAudio = audios[currentAudioCount];       playGlobalAudioFunction(currentAudio, playNext);   };   playNext(); },
  "shareFacebook": function(url){    window.open('https://www.facebook.com/sharer/sharer.php?u=' + url, '_blank'); },
  "playGlobalAudioWhilePlay": function(playList, index, audio, endCallback){    var changeFunction = function(event){       if(event.data.previousSelectedIndex == index){           this.stopGlobalAudio(audio);           if(isPanorama) {               var media = playListItem.get('media');               var audios = media.get('audios');               audios.splice(audios.indexOf(audio), 1);               media.set('audios', audios);           }           playList.unbind('change', changeFunction, this);           if(endCallback)               endCallback();       }   };   var audios = window.currentGlobalAudios;   if(audios && audio.get('id') in audios){       audio = audios[audio.get('id')];       if(audio.get('state') != 'playing'){           audio.play();       }       return;   }   playList.bind('change', changeFunction, this);   var playListItem = playList.get('items')[index];   var isPanorama = playListItem.get('class') == 'PanoramaPlayListItem';   if(isPanorama) {       var media = playListItem.get('media');       var audios = (media.get('audios') || []).slice();       if(audio.get('class') == 'MediaAudio') {           var panoramaAudio = this.rootPlayer.createInstance('PanoramaAudio');           panoramaAudio.set('autoplay', false);           panoramaAudio.set('audio', audio.get('audio'));           panoramaAudio.set('loop', audio.get('loop'));           panoramaAudio.set('id', audio.get('id'));           audio = panoramaAudio;       }       audios.push(audio);       media.set('audios', audios);   }   this.playGlobalAudio(audio, endCallback); },
  "playGlobalAudio": function(audio, endCallback){    var endFunction = function(){       audio.unbind('end', endFunction, this);       this.stopGlobalAudio(audio);       if(endCallback)           endCallback();   };   audio = this.getGlobalAudio(audio);   var audios = window.currentGlobalAudios;   if(!audios){       audios = window.currentGlobalAudios = {};   }   audios[audio.get('id')] = audio;   if(audio.get('state') == 'playing'){       return;   }   if(!audio.get('loop')){       audio.bind('end', endFunction, this);   }   audio.play(); },
  "showPopupPanoramaVideoOverlay": function(popupPanoramaOverlay, closeButtonProperties){    var self = this;   var showEndFunction = function() {       popupPanoramaOverlay.unbind('showEnd', showEndFunction);       closeButton.bind('click', hideFunction, this);       setCloseButtonPosition();       closeButton.set('visible', true);   };   var endFunction = function() {       if(!popupPanoramaOverlay.get('loop'))           hideFunction();   };   var hideFunction = function() {       self.MainViewer.set('toolTipEnabled', true);       if(!self.isCardboardViewMode())           popupPanoramaOverlay.set('visible', false);       closeButton.set('visible', false);       closeButton.unbind('click', hideFunction, this);       popupPanoramaOverlay.unbind('end', endFunction, self);       self.resumePlayers(playersPaused, true);       self.resumeGlobalAudios();   };   var setCloseButtonPosition = function() {       var right = 10;       var top = 10;       closeButton.set('right', right);       closeButton.set('top', top);   };   this.MainViewer.set('toolTipEnabled', false);   var closeButton = this.closeButtonPopupPanorama;   if(closeButtonProperties){       for(var key in closeButtonProperties){           closeButton.set(key, closeButtonProperties[key]);       }   }   var playersPaused = this.pauseCurrentPlayers(true);   this.pauseGlobalAudios();   popupPanoramaOverlay.bind('end', endFunction, this, true);   popupPanoramaOverlay.bind('showEnd', showEndFunction, this, true);   popupPanoramaOverlay.set('visible', true); },
  "resumePlayers": function(players, onlyResumeCameraIfPanorama){    for(var i = 0; i<players.length; ++i){       var player = players[i];       if(onlyResumeCameraIfPanorama && player.get('class') == 'PanoramaPlayer' && typeof player.get('video') === 'undefined'){           player.resumeCamera();       }       else{           player.play();       }   } },
  "showWindow": function(w, autoCloseMilliSeconds, containsAudio){    var closeFunction = function(){       clearAutoClose();       this.resumePlayers(playersPaused, !containsAudio);       w.unbind('close', closeFunction, this);   };   var clearAutoClose = function(){       w.unbind('click', clearAutoClose, this);       if(timeoutID != undefined){           clearTimeout(timeoutID);       }   };   var timeoutID = undefined;   if(autoCloseMilliSeconds){       var autoCloseFunction = function(){           w.hide();       };       w.bind('click', clearAutoClose, this);       timeoutID = setTimeout(autoCloseFunction, autoCloseMilliSeconds);   }   var playersPaused = this.pauseCurrentPlayers(!containsAudio);   w.bind('close', closeFunction, this);   w.show(this, true); },
  "getKey": function(key){    return window[key]; },
  "startPanoramaWithCamera": function(panorama, camera){    var playLists = this.getByClassName('PlayList');   if(playLists.length == 0)       return;    var restoreItems = [];   for(var i = 0, count = playLists.length; i<count; ++i){       var playList = playLists[i];       var items = playList.get('items');       for(var j = 0, countJ = items.length; j<countJ; ++j){           var item = items[j];           if(item.get('media') == panorama && item.get('class') == 'PanoramaPlayListItem'){               restoreItems.push({camera: item.get('camera'), item: item});               item.set('camera', camera);           }       }   }   if(restoreItems.length > 0) {       var restoreCameraOnStop = function(){           for (var i = 0; i < restoreItems.length; i++) {               restoreItems[i].item.set('camera', restoreItems[i].camera);           }           restoreItems[0].item.unbind('stop', restoreCameraOnStop, this);       };       restoreItems[0].item.bind('stop', restoreCameraOnStop, this);   } },
  "resumeGlobalAudios": function(caller){    if(window.currentGlobalAudiosActionCaller && window.currentGlobalAudiosActionCaller != caller)       return;   window.currentGlobalAudiosActionCaller = undefined;   var audios = window.currentGlobalAudios;   if(!audios) return;   for(var audio in audios){       audios[audio].play();   } },
  "updateMediaLabelFromPlayList": function(playList, htmlText, playListItemStopToDispose){    var changeFunction = function(){       var index = playList.get('selectedIndex');       if(index >= 0){           var beginFunction = function(){               playListItem.unbind('begin', beginFunction);               setMediaLabel(index);           };           var setMediaLabel = function(index){               var media = playListItem.get('media');               var text = media.get('data');               if(!text)                   text = media.get('label');               setHtml(text);           };           var setHtml = function(text){               if(text !== undefined)                   htmlText.set('html', '<div style=\"text-align:left\"><SPAN STYLE=\"color:#FFFFFF;font-size:12px;font-family:Verdana\"><span color=\"white\" font-family=\"Verdana\" font-size=\"12px\">' + text + '</SPAN></div>');               else                   htmlText.set('html', '');           };           var playListItem = playList.get('items')[index];           if(htmlText.get('html')){               setHtml('Loading...');               playListItem.bind('begin', beginFunction);           }           else{               setMediaLabel(index);           }       }   };   var disposeFunction = function(){       htmlText.set('html', undefined);       playList.unbind('change', changeFunction, this);       playListItemStopToDispose.unbind('stop', disposeFunction, this);   };   if(playListItemStopToDispose){       playListItemStopToDispose.bind('stop', disposeFunction, this);   }   playList.bind('change', changeFunction, this);   changeFunction(); },
  "stopGlobalAudio": function(audio){    var audios = window.currentGlobalAudios;   if(audios){       audio = audios[audio.get('id')];       delete audios[audio.get('id')];   }   audio.stop(); },
  "autotriggerAtStart": function(player, callback){    var stateChangeFunction = function(event){        if(event.data.state == 'playing'){           callback();           player.unbind('stateChange', stateChangeFunction, this);       }   };   player.bind('stateChange', stateChangeFunction, this); },
  "syncPlaylists": function(playLists){    var changeToMedia = function(media, playListDispatched){       for(var i = 0, count = playLists.length; i<count; ++i){           var playList = playLists[i];           if(playList != playListDispatched){               var items = playList.get('items');               for(var j = 0, countJ = items.length; j<countJ; ++j){                   if(items[j].get('media') == media){                       if(playList.get('selectedIndex') != j){                           playList.set('selectedIndex', j);                       }                       break;                   }               }           }       }   };   var changeFunction = function(event){       var playListDispatched = event.source;       var selectedIndex = playListDispatched.get('selectedIndex');       if(selectedIndex < 0)           return;       var media = playListDispatched.get('items')[selectedIndex].get('media');       changeToMedia(media, playListDispatched);   };   var mapPlayerChangeFunction = function(event){       var panoramaMapLocation = event.source.get('panoramaMapLocation');       if(panoramaMapLocation){           var map = panoramaMapLocation.get('map');           changeToMedia(map);       }   };   for(var i = 0, count = playLists.length; i<count; ++i){       playLists[i].bind('change', changeFunction, this);   }   var mapPlayers = this.getByClassName('MapPlayer');   for(var i = 0, count = mapPlayers.length; i<count; ++i){       mapPlayers[i].bind('panoramaMapLocation_change', mapPlayerChangeFunction, this);   } },
  "changeBackgroundWhilePlay": function(playList, index, color){    var changeFunction = function(event){       if(event.data.previousSelectedIndex == index){           playList.unbind('change', changeFunction, this);           if((color == viewerArea.get('backgroundColor')) && (colorRatios == viewerArea.get('backgroundColorRatios'))){               viewerArea.set('backgroundColor', backgroundColorBackup);               viewerArea.set('backgroundColorRatios', backgroundColorRatiosBackup);           }       }   };   var playListItem = playList.get('items')[index];   var player = playListItem.get('player');   var viewerArea = player.get('viewerArea');   var backgroundColorBackup = viewerArea.get('backgroundColor');   var backgroundColorRatiosBackup = viewerArea.get('backgroundColorRatios');   var colorRatios = [0];   if((color != backgroundColorBackup) || (colorRatios != backgroundColorRatiosBackup)){       viewerArea.set('backgroundColor', color);       viewerArea.set('backgroundColorRatios', colorRatios);       playList.bind('change', changeFunction, this);   } },
  "updateVideoCues": function(playList, index){    var playListItem = playList.get('items')[index];   var video = playListItem.get('media');   if(video.get('cues').length == 0)       return;   var player = playListItem.get('player');   var cues = [];   var changeFunction = function(){       if(playList.get('selectedIndex') != index){           video.unbind('cueChange', cueChangeFunction, this);           playList.unbind('change', changeFunction, this);       }   };   var cueChangeFunction = function(event){       var activeCues = event.data.activeCues;       for(var i = 0, count = cues.length; i<count; ++i){           var cue = cues[i];           if(activeCues.indexOf(cue) == -1 && (cue.get('startTime') > player.get('currentTime') || cue.get('endTime') < player.get('currentTime')+0.5)){               cue.trigger('end');           }       }       cues = activeCues;   };   video.bind('cueChange', cueChangeFunction, this);   playList.bind('change', changeFunction, this); },
  "setComponentVisibility": function(component, visible, applyAt, effect, propertyEffect, ignoreClearTimeout){    this.unregisterKey('visibility_'+component.get('id'));   var changeVisibility = function(){        if(effect && propertyEffect){            component.set(propertyEffect, effect);        }        component.set('visible', visible);       if(component.get('class') == 'ViewerArea'){           try{               if(visible) component.restart();               else        component.pause();           }           catch(e){};       }   };   var effectTimeoutName = 'effectTimeout_'+component.get('id');   if(!ignoreClearTimeout && window.hasOwnProperty(effectTimeoutName)){       var effectTimeout = window[effectTimeoutName];       if(effectTimeout instanceof Array){           for(var i=0; i<effectTimeout.length; i++){ clearTimeout(effectTimeout[i]) }       }else{           clearTimeout(effectTimeout);       }       delete window[effectTimeoutName];   }   else if(visible == component.get('visible') && !ignoreClearTimeout)       return;   if(applyAt && applyAt > 0){       var effectTimeout = setTimeout(function(){            if(window[effectTimeoutName] instanceof Array) {                var arrayTimeoutVal = window[effectTimeoutName];               var index = arrayTimeoutVal.indexOf(effectTimeout);               arrayTimeoutVal.splice(index, 1);               if(arrayTimeoutVal.length == 0){                   delete window[effectTimeoutName];               }           }else{               delete window[effectTimeoutName];            }           changeVisibility();        }, applyAt);       if(window.hasOwnProperty(effectTimeoutName)){           window[effectTimeoutName] = [window[effectTimeoutName], effectTimeout];       }else{           window[effectTimeoutName] = effectTimeout;       }   }   else{       changeVisibility();   } },
  "executeFunctionWhenChange": function(playList, index, endFunction, changeFunction){    var self = this;   var endObject = undefined;   var changePlayListFunction = function(event){       if(event.data.previousSelectedIndex == index){           if(changeFunction) changeFunction();           if(endFunction) endObject.unbind('end', endFunction, self);           playList.unbind('change', changePlayListFunction, self);       }   };   if(endFunction){       var playListItem = playList.get('items')[index];       var playListItemClass = playListItem.get('class');       if(playListItemClass == 'PanoramaPlayListItem'){           var camera = playListItem.get('camera');           endObject = camera.get('initialSequence');           if(!endObject) return;       }       else{           endObject = playListItem.get('media');       }       endObject.bind('end', endFunction, this);   }   playList.bind('change', changePlayListFunction, this); },
  "visibleComponentsIfPlayerFlagEnabled": function(components, playerFlag){    var enabled = this.get(playerFlag);   for(var i in components){       components[i].set('visible', enabled);   } },
  "setEndToItemIndex": function(playList, fromIndex, toIndex){    var endFunction = function(){       if(playList.get('selectedIndex') == fromIndex)           playList.set('selectedIndex', toIndex);   };   this.executeFunctionWhenChange(playList, fromIndex, endFunction); },
  "getActivePlayerWithViewer": function(viewerArea){    var players = this.getByClassName('PanoramaPlayer');   players = players.concat(this.getByClassName('VideoPlayer'));   players = players.concat(this.getByClassName('Video360Player'));   players = players.concat(this.getByClassName('PhotoAlbumPlayer'));   players = players.concat(this.getByClassName('MapPlayer'));   var i = players.length;   while(i-- > 0){       var player = players[i];       if(player.get('viewerArea') == viewerArea) {           var playerClass = player.get('class');           if(playerClass == 'PanoramaPlayer' && player.get('panorama') != undefined) return player;           else if((playerClass == 'VideoPlayer' || playerClass == 'Video360Player') && player.get('video') != undefined) return player;           else if(playerClass == 'PhotoAlbumPlayer' && player.get('photoAlbum') != undefined) return player;           else if(playerClass == 'MapPlayer' && player.get('map') != undefined) return player;       }   }   return undefined; },
  "registerKey": function(key, value){    window[key] = value; },
  "getGlobalAudio": function(audio){    var audios = window.currentGlobalAudios;   if(audios != undefined && audio.get('id') in audios){       audio = audios[audio.get('id')];   }   return audio; },
  "unregisterKey": function(key){    delete window[key]; },
  "setMainMediaByIndex": function(index){    if(index >= 0 && index < this.mainPlayList.get('items').length){       this.mainPlayList.set('selectedIndex', index);   } },
  "existsKey": function(key){    return key in window; },
  "setMainMediaByName": function(name){    var items = this.mainPlayList.get('items');   for(var i = 0; i<items.length; ++i){       if(items[i].get('media').get('label') == name) {           this.mainPlayList.set('selectedIndex', i);           return;       }   } },
  "getPlayListWithMedia": function(media, onlySelected){    var playLists = this.getByClassName('PlayList');   for(var i = 0, count = playLists.length; i<count; ++i){       var playList = playLists[i];       if(onlySelected && playList.get('selectedIndex') == -1)           continue;       var items = playList.get('items');       for(var j = 0, countJ = items.length; j<countJ; ++j){           if(items[j].get('media') == media)               return playList;       }   }   return undefined; }
 },
 "mouseWheelEnabled": true,
 "borderRadius": 0,
 "contentOpaque": false,
 "width": "100%",
 "shadow": false,
 "height": "100%",
 "paddingLeft": 0,
 "backgroundPreloadEnabled": true,
 "scrollBarVisible": "rollOver",
 "verticalAlign": "top",
 "paddingTop": 0,
 "scrollBarWidth": 10,
 "class": "Player",
 "minWidth": 20,
 "scrollBarMargin": 2,
 "overflow": "visible",
 "paddingBottom": 0,
 "id": "rootPlayer",
 "minHeight": 20,
 "horizontalAlign": "left",
 "gap": 10
})